import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Logo from "../assets/Aqualectra_logo.png"; // OPTIONAL LOGO

/* ------------------------------------------------------
 * Helper: Draws a full-width blue header banner
 * ------------------------------------------------------ */
function drawHeaderBanner(doc, title) {
  const width = doc.internal.pageSize.getWidth();

  // Banner background
  doc.setFillColor(41, 128, 185);
  doc.rect(0, 0, width, 30, "F");

  // Title text
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255);
  doc.text(title, 14, 20);

  // Optional logo
  try {
    doc.addImage(Logo, "PNG", width - 45, 5, 35, 20);
  } catch {}
}

/* ------------------------------------------------------
 * TURBINE DETAILS: Export chart + KPIs PDF
 * ------------------------------------------------------ */
export const exportTurbinePDF = (chartRef, turbineName, date, metadata = {}) => {
  if (!chartRef?.current?.canvas) return;

  const canvas = chartRef.current.canvas;
  const imgData = canvas.toDataURL("image/png");
  const doc = new jsPDF("landscape");

  drawHeaderBanner(doc, `${turbineName} - Performance Report`);

  // Info section
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(60);

  let y = 40;
  const line = (text) => {
    doc.text(text, 14, y);
    y += 8;
  };

  line(`Date: ${date}`);
  if (metadata.deviceId) line(`Device ID: ${metadata.deviceId}`);
  if (metadata.latitude && metadata.longitude)
    line(`Location: ${metadata.latitude.toFixed(5)}, ${metadata.longitude.toFixed(5)}`);
  if (metadata.capacity) line(`Rated Capacity: ${metadata.capacity} kW`);
  if (metadata.lastUpdated) line(`Last Updated: ${new Date(metadata.lastUpdated).toLocaleString()}`);

  doc.setLineWidth(0.4);
  doc.setDrawColor(180);
  doc.line(14, y + 2, 285, y + 2);
  y += 10;

  /* ---------- CHART SECTION ---------- */
  const chartWidth = 250;
  const chartHeight = 110;
  const chartX = (doc.internal.pageSize.getWidth() - chartWidth) / 2;

  doc.setFillColor(255);
  doc.setDrawColor(200);
  doc.roundedRect(chartX - 5, y - 3, chartWidth + 10, chartHeight + 10, 3, 3, "S");

  doc.addImage(imgData, "PNG", chartX, y, chartWidth, chartHeight);

  /* ---------- SUMMARY TABLE ---------- */
  const data = chartRef.current.data?.datasets;
  if (data && data.length >= 2) {
    const forecast = data[0].data.filter((v) => v != null);
    const realtime = data[1].data.filter((v) => v != null);

    const avg = (arr) => (arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : 0);

    const dailyTotals = {
      forecastMWh: forecast.reduce((a, b) => a + b / 6, 0) / 1000,
      realtimeMWh: realtime.reduce((a, b) => a + b / 6, 0) / 1000,
    };

    const accuracy =
      dailyTotals.forecastMWh === 0
        ? 0
        : 100 -
          Math.abs(
            (dailyTotals.realtimeMWh - dailyTotals.forecastMWh) /
              dailyTotals.forecastMWh
          ) *
            100;

    const summary = [
      ["Metric", "Value"],
      ["Max Forecast (kW)", Math.max(...forecast).toFixed(2)],
      ["Max Real-Time (kW)", Math.max(...realtime).toFixed(2)],
      ["Avg Forecast (kW)", avg(forecast).toFixed(2)],
      ["Avg Real-Time (kW)", avg(realtime).toFixed(2)],
      ["Total Forecast Energy (MWh)", dailyTotals.forecastMWh.toFixed(3)],
      ["Total Real-Time Energy (MWh)", dailyTotals.realtimeMWh.toFixed(3)],
      ["Forecast Accuracy (%)", accuracy.toFixed(2)],
    ];

    autoTable(doc, {
      startY: y + chartHeight + 20,
      head: [summary[0]],
      body: summary.slice(1),
      theme: "grid",
      styles: { fontSize: 11, cellPadding: 3, lineColor: 200, lineWidth: 0.1 },
      headStyles: { fillColor: [41, 128, 185], textColor: 255 },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(10);
  doc.setTextColor(120);
  doc.text(
    "Generated by Aqualectra | Wind Data Monitoring",
    doc.internal.pageSize.getWidth() / 2,
    pageHeight - 8,
    { align: "center" }
  );

  doc.save(`${turbineName}_report_${date}.pdf`);
};

/* ------------------------------------------------------
 * EXPORT CSV
 * ------------------------------------------------------ */
export const exportTurbineCSV = (
  lineChartData,
  turbineName,
  date,
  selectedSummary = null
) => {
  if (!lineChartData) return;

  const headers = [
    "Time",
    "Forecast (kW)",
    "Real-Time (kW)",
    "Delta (kW)",
    "Absolute Error (kW)",
    "Cumulative Forecast (kWh)",
    "Cumulative Real-Time (kWh)",
  ];

  let cumulativeForecast = 0;
  let cumulativeRealtime = 0;

  const rows = lineChartData.labels.map((label, i) => {
    const f = lineChartData.datasets[0]?.data[i] ?? 0;
    const r = lineChartData.datasets[1]?.data[i] ?? 0;

    cumulativeForecast += f / 6;
    cumulativeRealtime += r / 6;

    return [
      label,
      f,
      r,
      r - f,
      Math.abs(r - f),
      cumulativeForecast.toFixed(2),
      cumulativeRealtime.toFixed(2),
    ];
  });

  rows.push([]);
  rows.push(["Total Forecast (MWh)", (cumulativeForecast / 1000).toFixed(3)]);
  rows.push(["Total Real-Time (MWh)", (cumulativeRealtime / 1000).toFixed(3)]);
  rows.push([
    "Forecast Accuracy (%)",
    cumulativeForecast
      ? (
          100 - Math.abs((cumulativeRealtime - cumulativeForecast) / cumulativeForecast) * 100
        ).toFixed(2)
      : 0,
  ]);

  if (selectedSummary) {
    rows.push([]);
    rows.push(["Selected Hour", selectedSummary.hour]);
    rows.push(["Forecast", selectedSummary.forecast]);
    rows.push(["Real-Time", selectedSummary.realtime]);
  }

  const csvContent = [headers, ...rows].map((e) => e.join(",")).join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  link.download = `${turbineName}_data_${date}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
